# Generated by Django 2.2 on 2021-04-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=500)),
                ('dob', models.DateField(max_length=8)),
                ('mobile_number', models.CharField(max_length=12)),
                ('city', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('postal_code', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2)),
                ('appiled_for', models.CharField(choices=[('B', 'B.Sc'), ('M', 'M.Sc'), ('L', 'Law & humanities'), ('BB', 'BBA')], max_length=2)),
            ],
        ),
    ]
