# Generated by Django 2.2 on 2021-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=500)),
                ('message', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='admission',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='last_name',
        ),
        migrations.AddField(
            model_name='admission',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='admission',
            name='email',
            field=models.EmailField(default='', max_length=500),
        ),
    ]
